### ISSUE TITLE
Creeper walks on non-solid nodes

### ISSUE THREAD

**Issue by ExcaliburZero** [Rui914/creeper#3]
I was recently testing a setup where I would dig a chasm in between two sections of land and put a bridge of Ghoststone from the Mesecons mod to be able to cross it. I would then be able to disable the bridge in order to keep Creepers from crossing it.

However, when I set the Ghoststone nodes of the bridge to disappear the Creeper would still walk over them as if they were normal nodes. This is likely due to the Ghoststone nodes being changed into invisible nodes that the player can go through, rather than being outright removed.

I think the issue may be caused by the mod checking for air nodes rather than checking for nodes that entities can fall through.

**Comment by ExcaliburZero** [comment]
I think the issue might be in this section:
- https://github.com/Rui914/creeper/blob/master/function.lua#L203-L209

**Comment by Rui914** [comment]
41062cc
Fixed.
